apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: danushkarmdc/multi-server
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"
          - name: PGUSER
            value: postgresadmin
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: "5432"
          - name: PGDATABASE
            value: postgresdb
          - name: PGPASSWORD
            valueFrom:
                secretKeyRef:
                  key: PGPASSWORD
                  name: pgpassword